name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deps
      run: sudo apt install -y gcc-arm-none-eabi
    - name: FSBL
      run: |
        set -e
        git clone https://github.com/losfair/embeddedsw
        cd embeddedsw
        git checkout 92c4725f332c00331bd096192bb326ba3af45e8f
        cd lib/sw_apps/zynq_fsbl/src
        make || true # this will fail
        cd ../misc
        ./copy_bsp.sh
        make CC=arm-none-eabi-gcc
        cd ../src
        make
    - name: u-boot
      run: |
        set -e
        git clone https://github.com/Xilinx/u-boot-xlnx
        cd u-boot-xlnx
        git checkout xilinx-v2019.2
    - name: mkbootimage
      run: |
        set -e
        git clone https://github.com/antmicro/zynq-mkbootimage
        cd zynq-mkbootimage
        git checkout 29f7d69d115c20dc1b3a63810ebcb2451a7a1411
        make
