name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deps
      run: sudo apt update && sudo apt install -y gcc-arm-none-eabi gcc-arm-linux-gnueabihf libelf-dev
    - name: FSBL
      run: |
        set -e
        git clone https://github.com/losfair/embeddedsw
        cd embeddedsw
        git checkout 78c3d66dd80580a10a4dd801c10187bb9bd3046b
        cd lib/sw_apps/zynq_fsbl/src
        make "CFLAGS=-DFSBL_DEBUG_INFO"
    - name: u-boot
      run: |
        set -e
        git clone https://github.com/losfair/u-boot-xlnx
        cd u-boot-xlnx
        git checkout 69c2565fd1603de8b951b00894e6cf0957c06d96
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zynq_wbpf_defconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)
        ls -lash u-boot.elf
    - name: mkbootimage
      run: |
        set -e
        git clone https://github.com/antmicro/zynq-mkbootimage
        cd zynq-mkbootimage
        git checkout 29f7d69d115c20dc1b3a63810ebcb2451a7a1411
        make
        cp ../u-boot-xlnx/u-boot.elf ./
        cp ../embeddedsw/lib/sw_apps/zynq_fsbl/src/fsbl.elf ./
        ./mkbootimage ../build.bif ../BOOT.BIN
        ls -lash ../BOOT.BIN
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BOOT-BIN
        path: ./BOOT.BIN
