name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deps
      run: sudo apt update && sudo apt install -y gcc-arm-none-eabi gcc-arm-linux-gnueabihf libelf-dev
    - name: u-boot
      run: |
        set -e
        git clone https://github.com/losfair/u-boot-xlnx
        cd u-boot-xlnx
        git checkout 69c2565fd1603de8b951b00894e6cf0957c06d96
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zynq_wbpf_defconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)
        ls -lash u-boot.elf
    - name: linux
      run: |
        set -e
        git clone https://github.com/losfair/linux-xlnx
        cd linux-xlnx
        git checkout 92d07d7df3e6ef58cd24054f50664f461e03945c
        cp ../linux.config ./.config
        export ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf-
        make -j$(nproc)
    - name: mkbootimage
      run: |
        set -e
        git clone https://github.com/antmicro/zynq-mkbootimage
        cd zynq-mkbootimage
        git checkout 29f7d69d115c20dc1b3a63810ebcb2451a7a1411
        make
        cp ../linux-xlnx/arch/arm/boot/dts/zynq-wbpf.dtb ./
        cp ../linux-xlnx/arch/arm/boot/zImage ./
        cp ../u-boot-xlnx/u-boot.elf ./
        curl -sSL -o fsbl.elf https://s3.us-west-1.amazonaws.com/build-res.s3.univalent.net/zynq_fsbl_altk_7020.elf
        curl -sSL -o wbpf.bit https://s3.us-west-1.amazonaws.com/build-res.s3.univalent.net/wbpf-202203281430.bit
        ./mkbootimage ../build.bif ../BOOT.BIN
        ls -lash ../BOOT.BIN
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: BOOT-BIN
        path: ./BOOT.BIN
