name: CI
on:
  push:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Deps
      run: sudo apt install -y gcc-arm-none-eabi gcc-arm-linux-gnueabihf libelf-dev
    - name: FSBL
      run: |
        set -e
        git clone https://github.com/losfair/embeddedsw
        cd embeddedsw
        git checkout 50270870e6a78474404c5f443847ebc91f5d749b
        cd lib/sw_apps/zynq_fsbl/src
        make
    - name: u-boot
      run: |
        set -e
        git clone https://github.com/Xilinx/u-boot-xlnx
        cd u-boot-xlnx
        git checkout xilinx-v2019.2
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zynq_wbpf_defconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j$(nproc)
        ls -lash u-boot.elf
    - name: mkbootimage
      run: |
        set -e
        git clone https://github.com/antmicro/zynq-mkbootimage
        cd zynq-mkbootimage
        git checkout 29f7d69d115c20dc1b3a63810ebcb2451a7a1411
        make
        cp ../u-boot/u-boot.elf ./
        cp ../embeddedsw/lib/sw_apps/zynq_fsbl/src/fsbl.elf ./
        ./mkbootimg ./build.bif ./BOOT.BIN
        ls -lash BOOT.BIN
